# docker-compose.yml - With Node Exporter

version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus_config:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'YOUR PASSWORD'
      GF_SERVER_ROOT_URL: 'https://monitoring.adplay-mobile.com'
    restart: unless-stopped
    networks:
      - monitoring_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8088:80"
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - monitoring_net

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    command:
      - '--config.file=/etc/blackbox/config.yml'
    volumes:
      - ./blackbox_config/config.yml:/etc/blackbox/config.yml
    restart: unless-stopped
    networks:
      - monitoring_net

  # Optional: Add Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
    networks:
      - monitoring_net

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring_net:
    driver: bridge