# loki_config/loki-config.yml - Updated for 7-day log retention

auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_retain_period: 30s
  wal:
    dir: /loki/wal  

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  allow_structured_metadata: false
  retention_period: 168h  # 7 days - logs older than this will be deleted

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  retention_enabled: true  # Enable automatic cleanup
  retention_delete_delay: 2h  # Wait 2 hours before deleting
  retention_delete_worker_count: 150  # Number of workers for deletion
  delete_request_store: filesystem  # Required when retention is enabled