# scrape_configs/nodes.yml
scrape_configs:
- job_name: 'node_exporter'
  static_configs:
    - targets:
      - 'node-exporter:Port'        # DigitalOcean VM
      - 'IP:Port'      # AWS VM

- job_name: 'windows_exporter'
  static_configs:
    - targets: ['IP:Port']  #Azure VM